<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_mprm-category-content</name>
   <tag></tag>
   <elementGuidId>6b7791ef-16ed-4e7d-8d78-971d57adecd3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mprm-category-content</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-56&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;mprm-container mprm-shortcode-categories mprm-view-grid twentysixteen&quot;]/div[@class=&quot;mprm-row&quot;]/div[@class=&quot;mprm-menu-category mprm-effect-hover mprm-columns mprm-six&quot;]/a[@class=&quot;mprm-link&quot;]/div[@class=&quot;mprm-category-content&quot;]</value>
   </webElementProperties>
</WebElementEntity>
