<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>6297bee3-bf7d-4c25-84fb-01c4fc3c4555</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://localhost/wordpress/wp-content/plugins/mp-restaurant-menu/media//img/icon.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toplevel_page_edit-post_type-mp_menu_item&quot;)/a[@class=&quot;wp-has-submenu wp-not-current-submenu menu-top toplevel_page_edit?post_type=mp_menu_item menu-top-first&quot;]/div[@class=&quot;wp-menu-image dashicons-before&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
